# Generated by Django 4.0.2 on 2022-02-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operator_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel_num',
            field=models.BigIntegerField(),
        ),
    ]
